### PR TITLE
Ci GitHub actions

### LINKED ISSUE #3: Set up CI with Github-Actions
I as a code-owner want to automate testing of the codebase to avoid merging code with bugs or errors into the master branch.
For that I want to utilize Github-Actions to automatically run the existing tests (`make test`) on every pull-request to the repository.

### PR DESCRIPTION
**Pull request by jothepro**
fixes #3 

When ready this is supposed to build & test djinni automatically on every pull request & push.

Current status:
- ~~[x] build djinni standalone jar~~ (abandoned because it does not make sense)
- ~~[x] publish artifact that contains the jar~~ (same)
- [x] cache scala & djinni dependencies in build-job to reduce build-time
- [x] run automated tests from test-suite for Java (on ubuntu)
- [x] run automated tests from test-suite for Obj-C (on macos)
- ~~[ ] maybe run automated tests with different compilers & systems?~~ (dockerized tests currently fail: #12)

### CODE REVIEW

**Comment by a4z** [comment]
a very promising begin!

**Comment by jothepro** [comment]
Ok I think I am done.

## What this does:
- Builds djinni on `macos-latest` and runs the objc-tests.
- Builds djinni on `ubuntu-latest` and runs the java tests.

## Why is djinni built in both jobs?
To reduce execution-time, it would make sense to only build djinni once, create an artifact from the jar and then use it for both macos & ubuntu tests.
But the current djinni build setup is kind of weird: By default it only compiles to class-files without packaging them into a jar. This means I cannot simply create an artifact from the resulting jar and pass it over to the other action, but I have to build djinni on the system where I want to use it. I also cannot create an artifact from the collection of classfiles, because they have dependencies that have been installed to a cache in the home directory (`.ivy2`)
While there is an option to package a standalone jar, the test-scripts cannot make use of the resulting jar but rely on the default run-script that needs dependencies & classfiles being all over the place where it expects them to be to execute properly.

## Why are the dockerized tests not executed?
The dockerized tests currently fail locally on my machine and in the github workflow: #12. They need to be fixed before they can be enabled in the action.

**Comment by jothepro** [comment]
BTW i was confused why the workflow that I created is not executed in this MR. Then I found out that this is currently not possible to run actions on PRs opened from a fork due to security concerns: https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054 😢 
It seems like we cannot enforce a green pipeline as a Merge-Requirement in the PR because of this. The pipeline is only being executed in the fork, so we will need to check for its success manually on every PR from a fork...

**Comment by a4z** [comment]
this is interesting
for conan index center, there a tons of actions executed for every PR,  and if they are not green, no merge. and they are messages in the PR. 
example: https://github.com/conan-io/conan-center-index/pull/1137
maybe there is some trick ....

**Comment by jothepro** [comment]
Nevermind what I said, the information I gave was wrong: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories
Quote:
> When you create a pull request from a forked repository to the base repository, GitHub sends the pull_request event to the base repository and no pull request events occur on the forked repository.

I still don't know why it doesn't work in here, my theory is that it will work once we merged this branch (and thereby enabled actions for this repository). If you're fine with it I'd like to just give it a try by merging this and hoping for the best 😋

**Review by a4z — APPROVED** [review]

**Comment by a4z** [comment]
sure, release early, release often :-) 
great job btw!

**Review by bojanin — APPROVED** [review]

**Comment by bojanin** [comment]
lgtm!

**Pull request merged**
