### PR TITLE
Improvements & Updates to build process

### PR DESCRIPTION
**Pull request by jothepro**
## This PR is supposed to be
- a first step towards https://github.com/cross-language-cpp/djinni/issues/9
- an improvement to the issue with djinni being built multiple times in the current pipeline (see https://github.com/cross-language-cpp/djinni/pull/7#issuecomment-655721587 and https://github.com/cross-language-cpp/djinni/pull/14#issuecomment-669482695)

### Re-structuring of the build process
The current build & run of djinni depends on some bash scripts like `build`, `run`, `run-assume-built`.

I am not a fan of this kind of specific-use-case script wrappers, as they abstract away what really happens in a very intransparent way.

So I got rid of them and updated the build instructions. It's now all plain `sbt` calls, so anyone can understand or at least easily research whats going on during build & execution of djinni.

### Generation of standalone artifact

While the current `run`-script depends on a generated script that will load in all required classes from the `target` directory, I want to be able to build & run a standalone jar that needs no scripting-hell around it to work. In the current configuration a standalone jar can already be generated, but it is neither used by the `run` script, nor by the test-suite.

This is why I re-configuring the `sbt-assembly` plugin to be able to generate a standalone jar, that is even self-executing! No `java -jar`-gibberish, just call the binary and it will initiate java for you automatically! 💪 
```bash
$ ./djinni-standalone-0.1.0 --help
```

### Improved pipeline performance
With the standalone jar at hand, I can now optimize the pipeline. Currently djinni needs to be re-built in both `test-objc` & `test-java` jobs. This is because the test-stage dependes on all the scripts (`run` & friends) that depend on loading classes from all over the place.

The changes in the pipeline now make use of the standalone-jar, which is only built once.

### Update of dependencies
While I was re-writing the build, it was natural (and sometimes required) to update the dependencies:
- scala 2.12.7
- sbt ~~1.1.4~~ 1.3.13
- scala-parser-combinators 1.1.2
- snakeyaml 1.26
- scopt 3.5.0

The sbt update also required me to re-write the `build.sbt` entirely.

### Housekeeping

I deleted a lot of files, that I think are not needed:
- `.idea` folder: It would have needed re-configuration with all my changes, I was too lazy to update it. I don't think there is anything important in there anyways
- `support` folder containing a pre-configured sbt runner: I am open for discussion about this one. While reading docs about sbt & scala it appeared to me that it is not a common thing to do on scala projects, to add this kind of wrapper. I know this is often done with maven & gradle projects, but it seems not to be a standard thing in the scala world. So I discarded it as "optional". One reason why it may not be too common may be that the sbt-version is defined in a separate config-file anyways, so we don't need to depend on a wrapper script to call the correct version.

### TODO
While writing this PR these TODOs came to my mind, I will try to update the PR in the next days:
- [x] Update sbt to a more recent version
- [x] Update instructions on how to run djinni in the README.md: there is lots of references on how to run djinni by executing `src/run`, those will need to be replaced.
- [x] check Windows compatibility: Does the standalone jar execute on windows (cmd/powershell) as expected? Do the changes in the test-build work on windows?

### CODE REVIEW

**Comment by jothepro** [comment]
Update: I'm ready for a review now. I'm looking forward to finally being able to install djinni on my `PATH` and use it from my commandline like this: `djinni --help` 😍 
**Note:** As the current `run` & `run-assume-built` scripts have been removed, existing integration into your build-pipeline will break.

**Review by a4z — APPROVED** [review]
wonderful! 
There are of course parts outside of my current skill level, like some sbt script internals, but I checked out the PR branch and it works as the documentation says.

**Review by bojanin — COMMENTED** [review]
lgtm!

**Review by bojanin — APPROVED** [review]
lgtm!

**Pull request merged**
